name: sygeplejersken
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  # state management
  flutter_bloc: ^6.1.1
  hydrated_bloc: ^6.1.0
  equatable: ^1.2.5
  shared_preferences: '>=0.5.12+4 <2.0.0' # save user preferences

dev_dependencies:
  flutter_launcher_icons: ^0.8.1
  flutter_test:
    sdk: flutter

#flutter_icons:
#  android: true
#  ios: true
#  image_path_android: 'assets/icon/sialia_android.png'
#  image_path_ios: 'assets/icon/sialia_ios.png'
#  image_path: 'assets/icon/sialia.png'

flutter:
  uses-material-design: true
  #assets:
  #  - assets/icon/sialia_android.png
  #  - assets/icon/sialia_ios.png

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
